services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m debugpy --listen 0.0.0.0:5678 -m fastapi dev main.py --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./app:/app
    env_file:
      - .env

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
